/* The `cmds` language: a trivial imperative language.
 *
 *   print "hello,", "world";
 *   repeat 3 { print "tick", 1; }
 *
 * The interesting part is the shape of the semantic actions.  A classic yacc
 * action executes immediately during the reduce:
 *
 *     stmt: PRINT args ';'   { print_now($2); }
 *
 * Here instead each action builds a closure that *captures* the $1..$n
 * semantic values sitting on the reduce stack, and defers the work.  The
 * start rule hands the finished cmds::program to the driver, and
 * program::operator() executes the script later, as often as you like.
 */

%require "3.8"
%language "c++"
%header

/* Same namespace as the calc parser so both share one location type;
 * the distinct class name keeps the parsers apart. */
%define api.namespace {parse}
%define api.parser.class {cmds_parser}

%define api.token.raw
%define api.token.constructor
%define api.token.prefix {TOK_}
%define api.value.type variant
%define api.value.automove

%define parse.assert
%define parse.trace
%define parse.error detailed
%define parse.lac full

%locations
/* Reuse the location type generated by the calc grammar (gen/location.hh)
 * instead of generating a second, identical one.  With api.location.type
 * set, bison emits no location classes of its own; the #include in
 * %code requires supplies the shared ones. */
%define api.location.type {parse::location}

%param { cmds::driver& drv }

%code requires {
  #include <string>
  #include <vector>
  #include "cmds/program.hh"
  #include "location.hh"  /* the shared location type (see %locations above) */
  namespace cmds { class driver; }
}

%code {
  #include "cmds/driver.hh"
  /* Route the parser's yylex(drv) calls to this language's scanner. */
  #define yylex cmdslex
}

%token <std::string> STRING "string"
%token <int>         INT    "integer"
%token
  PRINT  "print"
  REPEAT "repeat"
  SEMI   ";"
  COMMA  ","
  LBRACE "{"
  RBRACE "}"
;

%nterm <cmds::program> script
%nterm <cmds::step> stmt
%nterm <std::vector<std::string>> items
%nterm <std::string> item

%printer { yyo << $$; } <int>;
%printer { yyo << '"' << $$ << '"'; } <std::string>;
%printer { yyo << ($$ ? "<step>" : "<no-op>"); } <cmds::step>;
%printer { yyo << "<program: " << $$.size() << " step(s)>"; } <cmds::program>;
%printer { yyo << $$.size() << " item(s)"; } <std::vector<std::string>>;

%%
%start unit;

unit:
  script  { drv.set_result($1); }
;

script:
  %empty       {}
| script stmt  { $$ = $1; $$.push($2); }
;

stmt:
  "print" items ";" {
      /* Capture the item list ($2) now; print it when the program runs. */
      $$ = [items = $2](std::ostream& os) {
        const char* sep = "";
        for (const std::string& item : items) {
          os << sep << item;
          sep = " ";
        }
        os << '\n';
      };
    }
| "repeat" "integer" "{" script "}" {
      /* A nested script is itself just a value: capture the count ($2) and
       * the body ($4), and run the body count times on execution. */
      $$ = [count = $2, body = $4](std::ostream& os) {
        for (int i = 0; i < count; ++i) body(os);
      };
    }
| error ";" {
      /* Recover at the next ';' so one bad statement doesn't hide later
       * diagnostics.  The empty step is dropped by program::push. */
      $$ = cmds::step();
      yyerrok;
    }
;

items:
  item            { $$.push_back($1); }
| items "," item  { $$ = $1; $$.push_back($3); }
;

item:
  "string"   { $$ = $1; }
| "integer"  { $$ = std::to_string($1); }
;
%%

void parse::cmds_parser::error(const location_type& l, const std::string& m) {
  drv.error(l, m);
}
